on:
  push:
    paths:
      - 'README.md'

jobs:
  modrinth-desc:
    if: github.ref == 'refs/heads/${{ github.event.repository.default_branch }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: funnyboy-roks/modrinth-auto-desc@v1.7
        with:
          auth-token: ${{ secrets.MODRINTH_AUTH_TOKEN }}
          slug: 'ByXE4W4q'
